### ISSUE TITLE
[meta] Implement the kafka output

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent-shipper#116]
**Describe the enhancement:**
Bringing the Elastic Agent more in line with outputs supported by Beats.

**Describe a specific use case for the enhancement or feature:**
Enable customers who are using beats to send events/logs to a Kafka broker to be able to create the same environment and functionality using the Elastic Agent. Lack of this capability may be an inhibitor for the adoption of Elastic Agent.

Tasks to complete:

- [x] Initial implementation #147 
- [x] #165 
- [x] #166 
- [x] #167 

Further related tasks
- [ ] #168
- [ ] #203
- [x] https://github.com/elastic/elastic-agent-shipper/issues/230
- [ ] https://github.com/elastic/elastic-agent-shipper/issues/232

**Comment by amitkanfer** [comment]
@jlind23 what's left for this issue?

**Comment by jlind23** [comment]
Please @cmacknz @leehinman keep me honest here but the remaining work is related to the two issues mentioned + the UI work that needs to be done: https://github.com/elastic/kibana/issues/143324

**Comment by amitkanfer** [comment]
@jlind23 if indeed this is the case and these 2 issues are blockers - can we assign them to a sprint? (The UI work is scheduled for sprint 9)

**Comment by pjaak** [comment]
Is there any ETA on the release of the Kafka output?

**Comment by jlind23** [comment]
@pjaak No concrete ETA for now but probably by the end of the summer.

**Comment by thethirstyturtle** [comment]
In an effort to further validate the requirement for this..

We have a large premium customer that is waiting for this functionality to be available in order to adopt Elastic Agent. All existing data collected with Beats are sent to Kafka. Without that functionality they are unable to move fully to Agent.

**Comment by cmacknz** [comment]
Thanks for confirming, we are actively working to support this soon. It's a very frequent ask and a known blocker for adopting agent.

**Comment by mbarretta** [comment]
Nudge to +1 (more like +10) the urgency of this feature

**Comment by cmacknz** [comment]
It is being worked on, but has been decoupled from the development of the shipper. Follow https://github.com/elastic/kibana/issues/143324 instead.

**Comment by dijkstrajesse** [comment]
@jlind23 Okay thanks for confirming. Is the Elastic Agent 8.10 (SNAPSHOT) binary available in the artifacts repo? It doesn't seem so?

**Comment by dijkstrajesse** [comment]
Apologies, accidentally hit close.

**Comment by jlind23** [comment]
@dijkstrajesse not in the public repo but should be available in the snapshot one.

**Comment by essodjolo** [comment]
Hi @jlind23. Does https://github.com/elastic/elastic-agent-shipper/issues/116#issuecomment-1651988393 mean that we can expect Kafka output in `8.10`?

**Comment by dijkstrajesse** [comment]
@essodjolo Yes. However, I tried and got the following error with the following Elastic Agent version: https://www.docker.elastic.co/r/beats/elastic-agent:8.10.0-SNAPSHOT. 
```
failed to prepare output \“default\“:: encountered unexpected output type while preparing outputs: kafka
```
Am I missing something or can you confirm this is a bug?

**Comment by jlind23** [comment]
@criamico @kevinlog do you know if the kafka tests already began?
Cc @cmacknz for awareness

**Comment by kevinlog** [comment]
@jlind23 

> do you know if the kafka tests already began?

@criamico and @szwarckonrad did some API level testing with real Agents.

> failed to prepare output \“default\“:: encountered unexpected output type while preparing outputs: kafka

Does the above error look familiar?  It looks like the Agent doesn't recognize the the output at all.

**Comment by jlind23** [comment]
Which is weird if you tell me that @criamico and @szwarckonrad were able to conduct tests with real agents. Might be a setup problems on @dijkstrajesse's end.
What's the kibana version you used to prepare this? Your entire stack was running 8.10.0-SNAPSHOT?

**Comment by kevinlog** [comment]
@jlind23 - I followed back up with @szwarckonrad - I was incorrect.  The testing that was done was at the API integration level, but not the actual Agent, so we may have a bug here.

here [is a gist](https://gist.github.com/szwarckonrad/ade11a52410d614cf51bf8f188445338) which shows an example Agent policy with Kafka output.  Is this what Agent would expect?

We will set up a cloud instance we can use for integration testing.  I think it will be best for us to work with someone from Agent team to stand up the Agent and connect with the kafka instance and we can see what the problem is.  cc @cmacknz 

> failed to prepare output \“default\“:: encountered unexpected output type while preparing outputs: kafka

Again, this error makes it seem like the Agent doesn't recognize the output at all, but I'm not sure.

Also reopening https://github.com/elastic/kibana/issues/143324 so that we can perform the e2e.  Apologies for the miscommunication on my end.

**Comment by faec** [comment]
Hi from the Agent team :-)

That particular error, "encountered unexpected output type while preparing outputs: kafka", is actually from Fleet Server not Agent (see https://github.com/elastic/fleet-server/blob/87d618e58d390bc272ed7bb6605488f41a59cc28/internal/pkg/policy/policy_output.go#L59), it looks like a new output type case needs to be added there.

Once Fleet lets the policy go through you will probably see a similar error on the Agent side until you update the appropriate [spec files](https://github.com/elastic/elastic-agent/tree/main/specs) to list `kafka` as a valid output type.

I've worked with the Kafka output and also with Agent spec files / output configuration, feel free to message me with questions (and feel free to ping on Slack since my github notifications latency is higher).

**Comment by nimarezainia** [comment]
@essodjolo @dijkstrajesse (and others) I do  appreciate that there is a lot of interest in this feature for agent (we also have a list of beta customers to reach out to). Could you please hold off on communicating 8.10 to any of our users until we have enough testing under our belts. Appreciate it.
