### ISSUE TITLE
Allow configuring the Elasticsearch output's timeouts and retry strategy

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#151]
Add support for configuring retry and timeout parameters in the Elasticsearch output.

Using the existing Elasticsearch output error and retry parameters as a guide, we should allow configuring the following parameters:

* The maximum number of retries before giving up on an event. See [max_retries](https://www.elastic.co/guide/en/beats/metricbeat/current/elasticsearch-output.html#_max_retries). Default to infinite_retry to match the behaviour of Filebeat.
* The retry backoff algorithm parameters. The Beats output exposes [backoff.init](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_backoff_init_2) and [backoff.max](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_backoff_max_2).
* The HTTP timeout used for the Elasticsearch client. See [timeout](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_timeout).
* The set of HTTP status codes that are considered retryable. This maps to the [RetryOnStatus](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8#Config) parameter in the go-elasticsearch client configuration.

These parameters must be mapped to the appropriate fields in the go-elasticsearch client configuration: https://pkg.go.dev/github.com/elastic/go-elasticsearch/v8#Config

**Comment by faec** [comment]
Clarification of one detail: `go-elasticsearch` doesn't (currently) support infinite retry. My opinion is that "infinite retry" is kind of misleading -- nothing can really retry forever, it is just a convention we fall back on because we lack a robust system for tracking and reporting permanent failure. So I'd rather we make real decisions about how to handle (finite) failure than add an "infinite retry" feature to the support library... but let's talk about the options in upcoming shipper meetings.

**Comment by cmacknz** [comment]
Not yet, I am going to open a follow up issue discuss what we want our strategy to be here.
