### ISSUE TITLE
Allow the Beats' shipper output to depend on the shipper client directly.

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#64]
The Beats' shipper output currently clones the the shipper's generated protobuf client to avoid a dependency cycle between the shipper and beats: https://github.com/elastic/beats/tree/main/libbeat/outputs/shipper/api

We need to break this dependency cycle and ensure the API is only defined in a single place. Decide on an approach and eliminate the duplication of the shipper API between beats and the shipper. Initial options include but are not limited to:

1. Removing the shipper's dependency on beats by moving the code it needs to https://github.com/elastic/elastic-agent-libs. In the long term we should do this regardless, but it may be easier to wait until the shipper prototype is complete to avoid delaying implementation with package moves: https://github.com/elastic/elastic-agent-shipper/issues/43
2. Move the shipper API definitions to separate repository specifically for the API definition and any reusable client code. The most obvious place is https://github.com/elastic/elastic-agent-client which is currently used for the agent control protocol. This would give developers a single repository to consume for working with the agent. The `elastic-agent-client` repository is currently owned by the agent control plane team.

**Comment by rdner** [comment]
I don't really like any of the listed options so far.

1. We cannot really remove the dependency on beats right now because some code in the shipper still depends on beats: the queue https://github.com/elastic/elastic-agent-shipper/blob/18fb98d457d6dd32977f63572e16b8ba46866348/queue/queue.go#L11-L12 and monitoring tests https://github.com/elastic/elastic-agent-shipper/blob/18fb98d457d6dd32977f63572e16b8ba46866348/monitoring/queuemon_test.go#L21 (second could probably be migrated to the libs).

2. The elastic-agent-client repository does not seem to contain the `.proto` files themselves only the generated Go files here https://github.com/elastic/elastic-agent-client/tree/main/pkg/proto if these files are supposed to be copied from another repository or automatically generated it's the same situation as we have now with Beats, so it does not solve much.

We should work on the queue to not depend on Beats, this is the proper solution IMO.
